spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQCJYGjNyz51v64J41ZmQCz7BsDKvjzUBwdmr8V5U2SGnCVpGKdqhTvPP9WsyLk2k24crdqSc9+BiLbjbZOgII1qnsSP7f0FiaMEvEum0sr/ZjUGrQnvQDNN0aDj5HMq+lv+0gnwceWThkOIgSrcWiy0C56Mz6smSlKli607ahhj9ero+4IZyURBx2W95Y1ZI8lciVXz0zPvGAEyCx3P1hOFodZ+/bBeAmO5mNcxima0kGGN6U9/MDgleIK/AcIaWmWbUzoVOJPmqSoGoEtYSTsRwu5eEG3MdJwhGrvvRqdv8GN0F3Df2pGu9BX0jkyWGEaLlqV+n/P5sNkIJK3bDNhZ6/BZWuJbgpy3CJXrItkBxuqFjmu255Xz7ErZzDT2meQ="

token:
  expirationTime: 86400000
  secret: "{cipher}0a55287d6d458db41ebac65c61851bb47ce6e801d9690e07f1615eb1377def11"

gateway:
  ip: 192.168.45.3

order_service:
  url: http://127.0.0.1/order-service/%s/orders
